# ===================================
#  Trust Me Bro — Report Generator
#  Creates PDF incident reports using
#  ReportLab
# ===================================

import os
import uuid
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from config import REPORTS_DIR


def generate_pdf(report_data):
    """
    Generate a professional PDF incident report.

    Parameters
    ----------
    report_data : dict
        Must contain: url, risk_score, classification, badge_class,
                      reasons, recommendations

    Returns
    -------
    str : filename of the generated PDF (relative to REPORTS_DIR)
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)

    filename = f"report_{uuid.uuid4().hex[:8]}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=15 * mm,
        rightMargin=15 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
    )

    styles = getSampleStyleSheet()
    elements = []

    # ---- Custom Styles ----
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=16,
        spaceAfter=3 * mm,
        textColor=colors.HexColor("#1e293b"),
    )
    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=11,
        spaceBefore=4 * mm,
        spaceAfter=2 * mm,
        textColor=colors.HexColor("#2563eb"),
    )
    body_style = ParagraphStyle(
        "BodyText",
        parent=styles["BodyText"],
        fontSize=9,
        leading=13,
    )
    small_style = ParagraphStyle(
        "SmallText",
        parent=styles["BodyText"],
        fontSize=8,
        textColor=colors.grey,
    )

    now = datetime.now()

    # ---- Title ----
    elements.append(Paragraph("Trust Me Bro — Incident Report", title_style))
    elements.append(
        Paragraph(
            f"Generated on {now.strftime('%d %B %Y')} at {now.strftime('%I:%M %p')}",
            small_style,
        )
    )
    elements.append(Spacer(1, 3 * mm))

    # ---- Summary Table ----
    elements.append(Paragraph("Summary", heading_style))

    classification = report_data.get("classification", "Unknown")
    risk_score = report_data.get("risk_score", 0)

    summary_data = [
        ["Field", "Value"],
        ["Analyzed URL", report_data.get("url", "N/A")],
        ["Risk Score", f"{risk_score} / 100"],
        ["Classification", classification],
    ]
    summary_table = Table(summary_data, colWidths=[45 * mm, 125 * mm])
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f1f5f9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    elements.append(summary_table)

    # ---- Indicators ----
    reasons = report_data.get("reasons", [])
    if reasons:
        elements.append(Paragraph("Phishing Indicators", heading_style))
        for i, reason in enumerate(reasons, 1):
            elements.append(Paragraph(f"{i}. {reason}", body_style))

    # ---- Recommendations ----
    recommendations = report_data.get("recommendations", [])
    if recommendations:
        elements.append(Paragraph("Recommendations", heading_style))
        for i, rec in enumerate(recommendations, 1):
            elements.append(Paragraph(f"{i}. {rec}", body_style))

    # ---- Footer ----
    elements.append(Spacer(1, 6 * mm))
    elements.append(
        Paragraph(
            "This report was automatically generated by Trust Me Bro — "
            "a phishing detection platform developed at GNIT.",
            small_style,
        )
    )

    doc.build(elements)
    return filename
